import { NextRequest, NextResponse } from "next/server"
import pool from "@/lib/db"
import { requireUser } from "@/lib/auth/session"
import { isTeacher } from "@/lib/auth/roles"
import { logAuditAction } from "@/lib/auth/audit"

// POST /api/clubs/[id]/claim-sponsor - Claim club as sponsor (teacher)
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const auth = await requireUser(request)
    if (!auth.ok) return auth.response
    const userId = auth.userId
    const { id: clubId } = await params
    const body = await request.json()
    const { confirmed } = body

    if (!confirmed) {
      return NextResponse.json(
        { success: false, error: "You must confirm that you are a sponsor/teacher of this club" },
        { status: 400 }
      )
    }

    // Verify user is a teacher (userType = 'None' from Azure AD)
    const isVerifiedTeacher = await isTeacher(userId)
    if (!isVerifiedTeacher) {
      return NextResponse.json(
        { success: false, error: "Only verified teachers can claim clubs as sponsors" },
        { status: 403 }
      )
    }

    // Check if club exists
    const clubResult = await pool.query(
      "SELECT name FROM clubs WHERE id = $1",
      [clubId]
    )

    if (clubResult.rows.length === 0) {
      return NextResponse.json(
        { success: false, error: "Club not found" },
        { status: 404 }
      )
    }

    const club = clubResult.rows[0]

    // Check if user is already a sponsor
    const existingSponsor = await pool.query(
      "SELECT id FROM club_sponsors WHERE club_id = $1 AND user_id = $2 AND status = 'active'",
      [clubId, userId]
    )

    if (existingSponsor.rows.length > 0) {
      return NextResponse.json(
        { success: false, error: "You are already a sponsor of this club" },
        { status: 409 }
      )
    }

    // Add as sponsor (id auto-generated by database). Leaving only marks the row
    // 'removed' (see leave-sponsor), and (club_id, user_id) is unique, so a
    // former sponsor coming back reactivates their old row instead of inserting.
    await pool.query(
      `INSERT INTO club_sponsors (club_id, user_id, status, assigned_at)
       VALUES ($1, $2, 'active', CURRENT_TIMESTAMP)
       ON CONFLICT (club_id, user_id)
       DO UPDATE SET status = 'active', assigned_at = CURRENT_TIMESTAMP`,
      [clubId, userId]
    )

    // Log audit action
    await logAuditAction({
      userId,
      action: "claim_sponsor",
      targetType: "club",
      targetId: clubId,
      details: `User claimed sponsorship of club: ${club.name}`,
    })

    return NextResponse.json({
      success: true,
      message: `You are now a sponsor of ${club.name}!`,
    })
  } catch (error) {
    console.error("Error claiming club as sponsor:", error)
    return NextResponse.json(
      { success: false, error: "Failed to claim club as sponsor" },
      { status: 500 }
    )
  }
}
