import { NextRequest, NextResponse } from "next/server"
import pool from "@/lib/db"
import { isPresidentOfClub, getClubSponsors } from "@/lib/auth/roles"
import { logAuditAction } from "@/lib/auth/audit"

// POST /api/clubs/[id]/leadership/request - Request leadership change (requires sponsor approval)
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id: clubId } = await params
    const body = await request.json()
    const { requestedBy, targetUserId, actionType, previousRole, newRole } = body

    if (!requestedBy || !targetUserId || !actionType) {
      return NextResponse.json(
        { success: false, error: "Missing required fields" },
        { status: 400 }
      )
    }

    // Verify requester is a president
    const isPresident = await isPresidentOfClub(requestedBy, clubId)
    if (!isPresident) {
      return NextResponse.json(
        { success: false, error: "Only presidents can request leadership changes" },
        { status: 403 }
      )
    }

    // Check if club has sponsors
    const sponsors = await getClubSponsors(clubId)
    if (sponsors.length === 0) {
      return NextResponse.json(
        { success: false, error: "This club has no sponsors. Leadership changes require sponsor approval." },
        { status: 400 }
      )
    }

    // Check for existing pending request for same user/action
    const existingRequest = await pool.query(
      `SELECT id FROM leadership_requests 
       WHERE club_id = $1 AND target_user_id = $2 AND action_type = $3 AND status = 'pending'`,
      [clubId, targetUserId, actionType]
    )

    if (existingRequest.rows.length > 0) {
      return NextResponse.json(
        { success: false, error: "A pending request already exists for this action" },
        { status: 409 }
      )
    }

    // Create leadership request (id auto-generated by database)
    const result = await pool.query(
      `INSERT INTO leadership_requests 
       (club_id, requested_by, target_user_id, action_type, previous_role, new_role, status, created_at)
       VALUES ($1, $2, $3, $4, $5, $6, 'pending', CURRENT_TIMESTAMP)
       RETURNING id`,
      [clubId, requestedBy, targetUserId, actionType, previousRole, newRole]
    )

    const requestId = result.rows[0].id

    // Log audit action
    await logAuditAction({
      userId: requestedBy,
      action: "create_leadership_request",
      targetType: "leadership_request",
      targetId: requestId,
      details: `Requested ${actionType} for user ${targetUserId}`,
    })

    return NextResponse.json({
      success: true,
      message: "Leadership change request submitted. Waiting for sponsor approval.",
      requestId,
    })
  } catch (error) {
    console.error("Error creating leadership request:", error)
    return NextResponse.json(
      { success: false, error: "Failed to create leadership request" },
      { status: 500 }
    )
  }
}

// GET /api/clubs/[id]/leadership/request - Get pending leadership requests
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id: clubId } = await params
    const { searchParams } = new URL(request.url)
    const userId = searchParams.get("userId")

    if (!userId) {
      return NextResponse.json(
        { success: false, error: "User ID required" },
        { status: 400 }
      )
    }

    // Get pending requests with user details
    const result = await pool.query(
      `SELECT 
        lr.*,
        requester.name as requester_name,
        requester.email as requester_email,
        target.name as target_name,
        target.email as target_email
      FROM leadership_requests lr
      JOIN users requester ON lr.requested_by = requester.id
      JOIN users target ON lr.target_user_id = target.id
      WHERE lr.club_id = $1 AND lr.status = 'pending'
      ORDER BY lr.created_at DESC`,
      [clubId]
    )

    return NextResponse.json({
      success: true,
      data: result.rows,
    })
  } catch (error) {
    console.error("Error fetching leadership requests:", error)
    return NextResponse.json(
      { success: false, error: "Failed to fetch leadership requests" },
      { status: 500 }
    )
  }
}
